load(":java_runtime_tests.bzl", "java_runtime_tests")
load(":java_toolchain_tests.bzl", "java_toolchain_tests")

package(default_applicable_licenses = ["@rules_java//:license"])

java_runtime_tests(name = "java_runtime_tests")

java_toolchain_tests(name = "java_toolchain_tests")
