load("//java:java_binary.bzl", "java_binary")

package(default_applicable_licenses = ["@rules_java//:license"])

java_binary(
    name = "hello_world",
    srcs = ["com/google/HelloWorld.java"],
    main_class = "com.google.HelloWorld",
)
