load(":java_runtime_tests.bzl", "java_runtime_tests")
load(":java_toolchain_tests.bzl", "java_toolchain_tests")

java_runtime_tests(name = "java_runtime_tests")

java_toolchain_tests(name = "java_toolchain_tests")
