load(":java_common_tests.bzl", "java_common_tests")
load(":java_info_tests.bzl", "java_info_tests")
load(":java_plugin_info_tests.bzl", "java_plugin_info_tests")

package(default_applicable_licenses = ["@rules_java//:license"])

java_common_tests(name = "java_common_tests")

java_info_tests(name = "java_info_tests")

java_plugin_info_tests(name = "java_plugin_info_tests")
