package(default_visibility = ["//visibility:public"])

licenses(["notice"])

config_setting(
    name = "javac9_language8",
    flag_values = {
        "@rules_java//java/constraints/language:host_version": "8",
        "@rules_java//java/constraints/javac:host_version": "9",
    }
)

config_setting(
    name = "javac10_language8",
    flag_values = {
        "@rules_java//java/constraints/language:host_version": "8",
        "@rules_java//java/constraints/javac:host_version": "10",
    }
)

config_setting(
    name = "javac11_language8",
    flag_values = {
        "@rules_java//java/constraints/language:host_version": "8",
        "@rules_java//java/constraints/javac:host_version": "11",
    }
)

config_setting(
    name = "javac12_language8",
    flag_values = {
        "@rules_java//java/constraints/language:host_version": "8",
        "@rules_java//java/constraints/javac:host_version": "12",
    }
)

config_setting(
    name = "jdk9",
    flag_values = {
        "@rules_java//java/constraints/runtime:host_version": "9",
    }
)

config_setting(
    name = "jdk10",
    flag_values = {
        "@rules_java//java/constraints/runtime:host_version": "10",
    }
)

config_setting(
    name = "jdk11",
    flag_values = {
        "@rules_java//java/constraints/runtime:host_version": "11",
    }
)

config_setting(
    name = "jdk12",
    flag_values = {
        "@rules_java//java/constraints/runtime:host_version": "12",
    }
)

config_setting(
    name = "remote_jdk9",
    flag_values = {
        "@rules_java//java/constraints/runtime:host_version": "9",
        "@rules_java//java/constraints/runtime:is_host_local": "remote",
    }
)

config_setting(
    name = "remote_jdk10",
    flag_values = {
        "@rules_java//java/constraints/runtime:host_version": "10",
        "@rules_java//java/constraints/runtime:is_host_local": "remote",
    }
)

config_setting(
    name = "remote_jdk11",
    flag_values = {
        "@rules_java//java/constraints/runtime:host_version": "11",
        "@rules_java//java/constraints/runtime:is_host_local": "remote",
    }
)

config_setting(
    name = "remote_jdk12",
    flag_values = {
        "@rules_java//java/constraints/runtime:host_version": "12",
        "@rules_java//java/constraints/runtime:is_host_local": "remote",
    }
)
