workspace(name = "integration_test_repo")

local_repository(
    name = "rules_java",
    path = "../../",
)

load("@rules_java//java:rules_java_deps.bzl", "rules_java_dependencies")

rules_java_dependencies()

load("@com_google_protobuf//bazel/private:proto_bazel_features.bzl", "proto_bazel_features")  # buildifier: disable=bzl-visibility

proto_bazel_features(name = "proto_bazel_features")

register_toolchains("//:all")

load("@rules_java//java:repositories.bzl", "rules_java_toolchains")

rules_java_toolchains()

load("@rules_java//java:http_jar.bzl", "http_jar")

http_jar(
    name = "my_jar",
    urls = ["file:///tmp/my_jar.jar"],
)
