config_setting(
	name = "javac10_source_8_target_8",
	flag_values = {
		"@rules_java//java/constraints:source_version": "8",
		"@rules_java//java/constraints:target_version": "8",
		"@rules_java//java/constraints:javac_version": "10",
	}
)

config_setting(
	name = "javac10_source_10_target_10",
	flag_values = {
		"@rules_java//java/constraints:source_version": "10",
		"@rules_java//java/constraints:target_version": "10",
		"@rules_java//java/constraints:javac_version": "10",
	}
)

