load(":javac_action_subject_tests.bzl", "javac_action_subject_tests")

package(default_applicable_licenses = ["@rules_java//:license"])

javac_action_subject_tests(name = "javac_action_subject_tests")
