package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = glob(["**"]) + [
        "//java/common/rules/impl:srcs",
    ],
    visibility = ["//java/common:__pkg__"],
)
