package(default_visibility = ["//visibility:public"])

load("@bazel_skylib//rules:common_settings.bzl", "string_flag")

string_flag(
	name = "version",
	build_setting_default = "8"
)

constraint_setting(name = "source")

constraint_value(
    name = "7",
    constraint_setting = ":source",
)

constraint_value(
    name = "8",
    constraint_setting = ":source",
)

constraint_value(
    name = "9",
    constraint_setting = ":source",
)

constraint_value(
    name = "10",
    constraint_setting = ":source",
)

constraint_value(
    name = "11",
    constraint_setting = ":source",
)

constraint_value(
    name = "12",
    constraint_setting = ":source",
)