load(":java_binary_tests.bzl", "java_binary_tests")
load(":merge_attrs_tests.bzl", "merge_attrs_test_suite")

merge_attrs_test_suite(name = "merge_attrs_tests")

java_binary_tests(name = "java_binary_tests")
